# Generated by Django 4.1.5 on 2023-01-09 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_orderitem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_price',
            field=models.FloatField(default=0.1),
        ),
    ]
